name: Publish package to PyPI
on:
  release:
    types: [created, edited]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.0'

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    name: Deploy on Pypi
    needs: run-ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check version matches
      run: |
        if [ -n "${{ github.event.release.tag_name }}" ]; then
          DEPLOY_VERSION=${{ github.event.release.tag_name }}
          DEPLOY_VERSION=${DEPLOY_VERSION:1}
        else
          DEPLOY_VERSION=${{ github.event.inputs.version }}
        fi
        make version-check DEPLOY_VERSION=$DEPLOY_VERSION

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install --upgrade pip build twine
        python -m build
        python -m twine upload dist/*
